---
controller_user_accounts:
  - user: "colin"
    is_superuser: false
    password: "redhat"

ah_collections:
  - collection_name: collection_test
    git_url: https://github.com/sean-m-sullivan/collection_test
