---
controller_user_accounts:
  - user: "colin"
    is_superuser: false
    password: "redhat"

controller_workflows:
- name: demoing
  description: ''
  extra_vars: {}
  organization:
  survey_enabled: false
  allow_simultaneous: false
  ask_variables_on_launch: false
  inventory:
  limit: ''
  scm_branch: ''
  ask_inventory_on_launch: false
  ask_scm_branch_on_launch: false
  ask_limit_on_launch: false
  webhook_service: "github"
  webhook_credential:
    organization:
      name: "Default"
      type: "organization"
    name: Github
    credential_type:
      name: "GitHub Personal Access Token"
      kind: "token"
      type: "credential_type"
    type: "credential"
  related:
    schedules: []
    workflow_nodes: []
    labels: []
    notification_templates_started: []
    notification_templates_success: []
    notification_templates_error: []
    notification_templates_approvals: []
    survey_spec: {}
